/* SPDX-License-Identifier: MIT */
/* Copyright © 2017-2022 Mark E Sowden <hogsy@oldtimes-software.com> */

/* Titan A.E. */
"GAMETEXT.TXT",              //0
        "EXPLORE\\BAN_1.FSK",//15
        "EXPLORE\\BAN_1.LND",//16
        "EXPLORE\\BAN_1.RAW",//17
        "EXPLORE\\BAN_1.RGN",//18
        "EXPLORE\\BAN_1.SPT",//19
        "EXPLORE\\BAN_1.XED",//20
        "EXPLORE\\BAN_2.FSK",//21
        "EXPLORE\\BAN_2.LND",//22
        "EXPLORE\\BAN_2.RAW",//23
        "EXPLORE\\BAN_2.RGN",//24
        "EXPLORE\\BAN_2.SPT",//25
        "EXPLORE\\BAN_2.XED",//26

        "EXPLORE\\DCH1_2.LND",//35

        "EXPLORE\\DERELIC1.FSK",//46
        "EXPLORE\\DERELIC1.LND",//47
        "EXPLORE\\DERELIC1.RAW",//48
        "EXPLORE\\DERELIC1.RGN",//49
        "EXPLORE\\DERELIC1.SPT",//50
        "EXPLORE\\DERELIC1.XED",//51
        "EXPLORE\\DERELIC2.FSK",//52
        "EXPLORE\\DERELIC2.LND",
        "EXPLORE\\DERELIC2.RAW",
        "EXPLORE\\DERELIC2.RGN",
        "EXPLORE\\DERELIC2.SPT",
        "EXPLORE\\DERELIC2.XED",//57
        "EXPLORE\\DERELIC3.FSK",//58
        "EXPLORE\\DERELIC3.LND",
        "EXPLORE\\DERELIC3.RAW",
        "EXPLORE\\DERELIC3.RGN",
        "EXPLORE\\DERELIC3.SPT",
        "EXPLORE\\DERELIC3.XED",//63

        "EXPLORE\\DREJ_1.FSK",//76
        "EXPLORE\\DREJ_1.LND",
        "EXPLORE\\DREJ_1.RAW",
        "EXPLORE\\DREJ_1.RGN",
        "EXPLORE\\DREJ_1.SPT",
        "EXPLORE\\DREJ_1.XED",
        "EXPLORE\\DREJ_2.FSK",//82
        "EXPLORE\\DREJ_2.LND",
        "EXPLORE\\DREJ_2.RAW",
        "EXPLORE\\DREJ_2.RGN",
        "EXPLORE\\DREJ_2.SPT",
        "EXPLORE\\DREJ_2.XED",//87
        "EXPLORE\\DREJ_3.FSK",//88
        "EXPLORE\\DREJ_3.LND",
        "EXPLORE\\DREJ_3.RAW",
        "EXPLORE\\DREJ_3.RGN",
        "EXPLORE\\DREJ_3.SPT",
        "EXPLORE\\DREJ_3.XED",//93
        "EXPLORE\\DREJ_4.FSK",//94
        "EXPLORE\\DREJ_4.LND",
        "EXPLORE\\DREJ_4.RGN",
        "EXPLORE\\DREJ_4.SPT",
        "EXPLORE\\DREJ_4.XED",  //99
        "EXPLORE\\FITECLUB.FSK",//100
        "EXPLORE\\FITECLUB.LND",
        "EXPLORE\\FITECLUB.RAW",
        "EXPLORE\\FITECLUB.RGN",
        "EXPLORE\\FITECLUB.SPT",
        "EXPLORE\\FITECLUB.XED",//105

        "EXPLORE\\RESLAB2.LND",//115

        "EXPLORE\\SESH1.FSK",//132
        "EXPLORE\\SESH1.LND",//133
        "EXPLORE\\SESH1.RAW",//134
        "EXPLORE\\SESH1.RGN",//135
        "EXPLORE\\SESH1.SPT",//136
        "EXPLORE\\SESH1.XED",//137
        "EXPLORE\\SESH2.FSK",//138
        "EXPLORE\\SESH2.LND",//139
        "EXPLORE\\SESH2.RAW",//140
        "EXPLORE\\SESH2.RGN",//141
        "EXPLORE\\SESH2.SPT",//142
        "EXPLORE\\SESH2.XED",//143

        "EXPLORE\\SHOOTGAL.FSK",//150
        "EXPLORE\\SHOOTGAL.LND",//151
        "EXPLORE\\SHOOTGAL.RAW",//152
        "EXPLORE\\SHOOTGAL.RGN",//153
        "EXPLORE\\SHOOTGAL.SPT",//154
        "EXPLORE\\SHOOTGAL.XED",//155

        "EXPLORE\\SLAVE1_1.LND",//157
        "EXPLORE\\SLAVE1_2.LND",//163
        "EXPLORE\\SLAVE1_3.LND",//169

        "EXPLORE\\TAU14_1.FSK",//174
        "EXPLORE\\TAU14_1.LND",//175
        "EXPLORE\\TAU14_1.RAW",//176
        "EXPLORE\\TAU14_1.RGN",//177
        "EXPLORE\\TAU14_1.SPT",//178
        "EXPLORE\\TAU14_1.XED",//179
        "EXPLORE\\TAU14_2.FSK",//180
        "EXPLORE\\TAU14_2.LND",//181
        "EXPLORE\\TAU14_2.RAW",//182
        "EXPLORE\\TAU14_2.RGN",//183
        "EXPLORE\\TAU14_2.SPT",//184
        "EXPLORE\\TAU14_2.XED",//185
        "EXPLORE\\TAU14_3.FSK",//186
        "EXPLORE\\TAU14_3.LND",//187
        "EXPLORE\\TAU14_3.RGN",//189
        "EXPLORE\\TAU14_3.SPT",//190
        "EXPLORE\\TAU14_3.XED",//191
        "EXPLORE\\TAU14_4.FSK",//192
        "EXPLORE\\TAU14_4.LND",//193
        "EXPLORE\\TAU14_4.RGN",//195
        "EXPLORE\\TAU14_4.SPT",//196
        "EXPLORE\\TAU14_4.XED",//197

        "EXPLORE\\TRADE1_1.LND",//216
        "EXPLORE\\TRADE1_2.LND",//222
        "EXPLORE\\TRADE1_3.LND",//228
        "EXPLORE\\TRADE1_4.LND",//234
        "EXPLORE\\VIGO1ST.LND", //246
        "EXPLORE\\VIGO_IN.LND", //258
        "EXPLORE\\VIGO_OUT.LND",//264

        "EXPLORE\\COMPUTER\\TAUCOM.PSI",//271
        "EXPLORE\\COMPUTER\\TAUCOM.SPT",//272

        "EXPLORE\\EVENTS\\DERELIC1.FUK",//277
        "EXPLORE\\EVENTS\\DERELIC2.FUK",//278
        "EXPLORE\\EVENTS\\DERELIC3.FUK",//279
        "EXPLORE\\EVENTS\\FITECLUB.FUK",//280
        "EXPLORE\\EVENTS\\SESH2.FUK",   //281
        "EXPLORE\\EVENTS\\SHOOTGAL.FUK",//282
        "EXPLORE\\EVENTS\\TAU14_1.FUK", //283
        "EXPLORE\\EVENTS\\TAU14_2.FUK", //284
        "EXPLORE\\EVENTS\\TAU14_3.FUK", //285
        "EXPLORE\\EVENTS\\TAU14_4.FUK", //286

        "EXPLORE\\EVENTS\\DREJ_1.FUK",//295
        "EXPLORE\\EVENTS\\DREJ_2.FUK",//296
        "EXPLORE\\EVENTS\\DREJ_3.FUK",//297
        "EXPLORE\\EVENTS\\DREJ_4.FUK",//298
        "EXPLORE\\EVENTS\\SESH1.FUK", //299

        "EXPLORE\\PICKUPS\\AMMO1.PSI",   //306
        "EXPLORE\\PICKUPS\\AMMO1.SPT",   //307
        "EXPLORE\\PICKUPS\\CAN.PSI",     //308
        "EXPLORE\\PICKUPS\\CAN.SPT",     //309
        "EXPLORE\\PICKUPS\\COOLANT.PSI", //310
        "EXPLORE\\PICKUPS\\COOLANT.SPT", //311
        "EXPLORE\\PICKUPS\\COOLBOX.PSI", //312
        "EXPLORE\\PICKUPS\\COOLBOX.SPT", //313
        "EXPLORE\\PICKUPS\\CRYSTBIT.PSI",//314
        "EXPLORE\\PICKUPS\\CRYSTBIT.SPT",//315
        "EXPLORE\\PICKUPS\\DONG.PSI",    //316
        "EXPLORE\\PICKUPS\\DONG.SPT",    //317
        "EXPLORE\\PICKUPS\\GUN1.PSI",    //318
        "EXPLORE\\PICKUPS\\GUN1.SPT",    //319
        "EXPLORE\\PICKUPS\\HEALTH1.PSI", //320
        "EXPLORE\\PICKUPS\\HEALTH1.SPT", //321
        "EXPLORE\\PICKUPS\\MEDPACK.PSI", //322
        "EXPLORE\\PICKUPS\\MEDPACK.SPT", //323
        "EXPLORE\\PICKUPS\\MEDPROBE.PSI",//324
        "EXPLORE\\PICKUPS\\MEDPROBE.SPT",//325
        "EXPLORE\\PICKUPS\\RD_KEY.PSI",  //326
        "EXPLORE\\PICKUPS\\RD_KEY.SPT",  //327
        "EXPLORE\\PICKUPS\\RD_KEY2.PSI", //328
        "EXPLORE\\PICKUPS\\RD_KEY2.SPT", //329

        "EXPLORE\\PICKUPS\\TRANSL8R.PSI",//332
        "EXPLORE\\PICKUPS\\TRANSL8R.SPT",//333
        "EXPLORE\\PICKUPS\\VP_CHIP.PSI", //334
        "EXPLORE\\PICKUPS\\VP_CHIP.SPT", //335
        "EXPLORE\\PICKUPS\\VP_KEY.PSI",  //336
        "EXPLORE\\PICKUPS\\VP_KEY.SPT",  //337
        "EXPLORE\\PICKUPS\\WRENCH.PSI",  //338
        "EXPLORE\\PICKUPS\\WRENCH.SPT",  //339
        "EXPLORE\\PICKUPS\\JAWBONE.PSI", //351
        "EXPLORE\\PICKUPS\\JAWBONE.SPT", //352
        "EXPLORE\\PICKUPS\\CLAWBONE.PSI",//353
        "EXPLORE\\PICKUPS\\CLAWBONE.SPT",//354

        "EXPLORE\\TEXANIM\\ASIGN.SPT", //357
        "EXPLORE\\TEXANIM\\B0ANIM.SPT",//358
        "EXPLORE\\TEXANIM\\BSIGN.SPT", //359
        "EXPLORE\\TEXANIM\\CHANIM.SPT",//360

        "EXPLORE\\TEXANIM\\CSLOT.SPT", //365
        "EXPLORE\\TEXANIM\\DCBOX2.SPT",//366
        "EXPLORE\\TEXANIM\\MSPARK.SPT",//376

        "EXPLORE\\TEXANIM\\PAW.SPT",//381

        "EXPLORE\\TEXANIM\\T14BLINK.SPT",//386
        "EXPLORE\\TEXANIM\\T14LITE.SPT", //387

        "EXPLORE\\WEAPONS\\CALEGUN1.PSI",        //398
        "EXPLORE\\WEAPONS\\CALEGUN1.SPT",        //399
        "EXPLORE\\WEAPONS\\WEAP.SPT",            //401
        "EXPLORE\\WEAPONS\\WRENCH.PSI",          //402
        "EXPLORE\\WEAPONS\\WRENCH.SPT",          //403
        "EXPLORE\\WEAPONS\\PROJECT\\MISSILE.PSI",//404
        "EXPLORE\\WEAPONS\\PROJECT\\MISSILE.SPT",//405
        "EXPLORE\\WEAPONS\\PROJECT\\SPIT.PSI",   //406
        "EXPLORE\\WEAPONS\\PROJECT\\SPIT.SPT",   //407

        "EXPLORE\\WEAPONS\\JAWBONE.PSI",  //410
        "EXPLORE\\WEAPONS\\JAWBONE.SPT",  //411
        "EXPLORE\\WEAPONS\\CLAWBONE.PSI", //412
        "EXPLORE\\WEAPONS\\CLAWBONE.SPT", //413
        "EXPLORE\\WRISTCOM\\IMAGES.SPT",  //414
        "EXPLORE\\WRISTCOM\\WRISTCOM.PSI",//415
        "EXPLORE\\WRISTCOM\\WRISTCOM.SPT",//416

        "EXPLORE\\ALIENFNT\\ALIEN1.SPT",//422

        "EXPLORE\\OSD\\CODEFRAG.SPT",//424

        "FLYING\\GLOBAL.SPT",           //426
        "FLYING\\IMP_VOLC.SPT",         //427
        "FLYING\\BACKDRPS\\ENDSCN1.RAW",//428
        "FLYING\\BACKDRPS\\ENDSCN2.RAW",//429
        "FLYING\\BACKDRPS\\ENDSCN3.RAW",//430
        "FLYING\\BACKDRPS\\VOLCANO.RAW",//431

        "FLYING\\LEVELS\\BANGKOK.SPT",//439

        "FLYING\\LEVELS\\BANGKOK2.PSI",//441
        "FLYING\\LEVELS\\BANGKOK2.SPT",//442

        "FLYING\\LEVELS\\BANGKTUN.SPT",//445

        "FLYING\\LEVELS\\CRASHUNI.PSI",//451
        "FLYING\\LEVELS\\CRASHUNI.SPT",//452

        "FLYING\\LEVELS\\SESH_UNI.SPT",//485

        "FLYING\\LEVELS\\TAU_PLAN.SPT",//496
        "FLYING\\LEVELS\\TAU_STAR.SPT",//497

        "FLYING\\LEVELS\\U_PLASMA.SPT",//508

        "FLYING\\LEVELS\\U_STARS.SPT",//510

        "FLYING\\LEVELS\\VOL_MOUN.PSI",//518
        "FLYING\\LEVELS\\VOL_MOUN.SPT",//519

        "FLYING\\LEVELS\\VOLC_SKY.PSI",//521
        "FLYING\\LEVELS\\VOLC_SKY.SPT",//522
        "FLYING\\LEVELS\\VOLCANO.RAD", //523
        "FLYING\\LEVELS\\VOLCANO.ROB", //524
        "FLYING\\LEVELS\\VOLCANO.SPT", //525
        "FLYING\\LEVELS\\VOLCANO.STF", //526

        "FLYING\\LEVELS\\SESH_UNI.PSI",//529

        "FLYING\\LEVELS\\TAU_PLAN.PSI",//537
        "FLYING\\LEVELS\\TAU_STAR.PSI",//538
        "FLYING\\LEVELS\\U_PLASMA.PSI",//539
        "FLYING\\LEVELS\\BANGKTUN.PSI",//540

        "FLYING\\LEVELS\\RACE_UNI.PSI",//543
        "FLYING\\LEVELS\\RACE_UNI.SPT",//544

        "FLYING\\OBJECTS\\PICKUP_B.PSI",//553

        "FLYING\\OBJECTS\\BANGKOK2.PSI",//557

        "FLYING\\OBJECTS\\BANGPIL2.PSI",//559
        "FLYING\\OBJECTS\\BANGPIL3.PSI",//560
        "FLYING\\OBJECTS\\BANGPIL4.PSI",//561
        "FLYING\\OBJECTS\\BANGPILL.PSI",//562
        "FLYING\\OBJECTS\\BCORAL.PSI",  //563
        "FLYING\\OBJECTS\\BCORAL2.PSI", //564

        "FLYING\\OBJECTS\\BOB.OBE",    //570
        "FLYING\\OBJECTS\\BOB.PSI",    //571
        "FLYING\\OBJECTS\\BOBHEAD.PSI",//572
        "FLYING\\OBJECTS\\BODY.PSI",   //573

        "FLYING\\OBJECTS\\BRANCH.PSI",//575

        "FLYING\\OBJECTS\\BUSH.PSI",    //577
        "FLYING\\OBJECTS\\C_HANGAR.PSI",//578

        "FLYING\\OBJECTS\\CRSHDOOR.PSI",//587

        "FLYING\\OBJECTS\\FB_ROCK.PSI",//634

        "FLYING\\OBJECTS\\FIRERING.PSI",//636

        "FLYING\\OBJECTS\\FRAKHEAD.PSI",//638

        "FLYING\\OBJECTS\\FRANK.PSI",//640

        "FLYING\\OBJECTS\\MISSILE.PSI",  //661
        "FLYING\\OBJECTS\\MISSILE.SPT",  //662
        "FLYING\\OBJECTS\\NME_SHOT.PSI", //663
        "FLYING\\OBJECTS\\SATLITE1.PSI", //692
        "FLYING\\OBJECTS\\SATLITE2.PSI", //693
        "FLYING\\OBJECTS\\SENTDREJ.PSI", //694
        "FLYING\\OBJECTS\\SERVPAN.PSI",  //695
        "FLYING\\OBJECTS\\SERVPAN2.PSI", //696
        "FLYING\\OBJECTS\\SERVPIPE.PSI", //697
        "FLYING\\OBJECTS\\SESHRK1.PSI",  //698
        "FLYING\\OBJECTS\\SESHRK2.PSI",  //699
        "FLYING\\OBJECTS\\SESHRK3.PSI",  //700
        "FLYING\\OBJECTS\\SESHRK4.PSI",  //701
        "FLYING\\OBJECTS\\SHADSENT.PSI", //703
        "FLYING\\OBJECTS\\SHAFT01.PSI",  //704
        "FLYING\\OBJECTS\\SKIN.PSI",     //708
        "FLYING\\OBJECTS\\SKINBOB.PSI",  //709
        "FLYING\\OBJECTS\\SKINFRANK.PSI",//710
        "FLYING\\OBJECTS\\SPARKYPJ.PSI", //711

        "FLYING\\OBJECTS\\STALICT.PSI", //713
        "FLYING\\OBJECTS\\STELLEAD.PSI",//714
        "FLYING\\OBJECTS\\STRUTH1.PSI", //715
        "FLYING\\OBJECTS\\STRUTV1.PSI", //716
        "FLYING\\OBJECTS\\TARSIS.PSI",  //717

        "FLYING\\OBJECTS\\TSS_L1.PSI",//725
        "FLYING\\OBJECTS\\TSS_L2.PSI",//726

        "FLYING\\OBJECTS\\VOLCANO.BFF", //738
        "FLYING\\OBJECTS\\WARPIN.PSI",  //739
        "FLYING\\OBJECTS\\WARPSTAR.PSI",//740
        "FLYING\\OBJECTS\\WPOD.PSI",    //741

        "FLYING\\OBJECTS\\HOVRBAR.PSI",//770
        "FLYING\\OBJECTS\\HOVRBAR.SPT",//771

        "FLYING\\OBJECTS\\SHKWAVE.PSI",//762
        "FLYING\\OBJECTS\\SHKWAVE.SPT",//763

        "FLYING\\SPRITES\\BOBSRING.SPR",//793

        "FLYING\\SPRITES\\BURN1.SPR",//796
        "FLYING\\SPRITES\\BURN2.SPR",//797

        "FLYING\\SPRITES\\BUSH.SPR", //799
        "FLYING\\SPRITES\\BUSH2.SPR",//800
        "FLYING\\SPRITES\\BUSH3.SPR",//801
        "FLYING\\SPRITES\\BUSH4.SPR",//802

        "FLYING\\SPRITES\\FBURST.SPR",  //852
        "FLYING\\SPRITES\\FIRE.SPR",    //853
        "FLYING\\SPRITES\\FIRE2.SPR",   //854
        "FLYING\\SPRITES\\FLOW.SPR",    //855
        "FLYING\\SPRITES\\FLOW2.SPR",   //856
        "FLYING\\SPRITES\\FRNKBALL.SPR",//857
        "FLYING\\SPRITES\\FTREE1.SPR",  //858
        "FLYING\\SPRITES\\FTREE2.SPR",  //859
        "FLYING\\SPRITES\\FTREE3.SPR",  //860

        "FLYING\\SPRITES\\IVIS.SPR",  //877
        "FLYING\\SPRITES\\KEYSPR.SPR",//878

        "FLYING\\SPRITES\\LAVASPL.SPR",//880

        "FLYING\\SPRITES\\SMOKIN2.SPR",//889

        "FLYING\\SPRITES\\SPRAY.SPR",//892

        "GRAPHICS\\ENVRO.SPT",   //921
        "GRAPHICS\\EXP_BLUE.PAL",//922
        "GRAPHICS\\EXP_DREJ.PAL",//923
        "GRAPHICS\\EXP_GEN.SPT", //924
        "GRAPHICS\\EXP_GREN.PAL",//925
        "GRAPHICS\\EXP_NEG.PAL", //926
        "GRAPHICS\\EXP_RED.PAL", //928
        "GRAPHICS\\EXP_WOOD.PAL",//929
        "GRAPHICS\\EXPLODE1.SPT",//930

        "GRAPHICS\\FONT12A.FON", //934
        "GRAPHICS\\FONT18.FON",  //935
        "GRAPHICS\\GEN_OVER.SPT",//936
        "GRAPHICS\\KORSO.SPT",   //937
        "GRAPHICS\\LENSFLAR.SPT",//938

        "GRAPHICS\\PARTICLES.SPT",//940

        "GRAPHICS\\TITANGEN.SPT",//944
        "GRAPHICS\\TRAILS.SPT",  //945

        "GRAPHICS\\FRONTEND\\MENU.RAW",//951

        "GRAPHICS\\LONGBOW.SPT", //965
        "GRAPHICS\\PHOENIX.SPT", //966
        "GRAPHICS\\SHUTTLE.SPT", //967
        "GRAPHICS\\VALKYRIE.SPT",//968
        "MODELS\\AKIMA.PSI",     //969
        "MODELS\\AKIMA.SPT",     //970
        "MODELS\\BADBIKE.PSI",   //971

        "MODELS\\BARMAN.PSI",  //973
        "MODELS\\BARMAN.SPT",  //974
        "MODELS\\BARREL.PSI",  //979
        "MODELS\\BARREL.SPT",  //980
        "MODELS\\BARREL1.PSI", //981
        "MODELS\\BIGFAN.PSI",  //989
        "MODELS\\BIGFAN.SPT",  //990
        "MODELS\\BIGHEAD.PSI", //991
        "MODELS\\BIGHEAD.SPT", //992
        "MODELS\\CALE.PSI",    //993
        "MODELS\\CALE.SPT",    //994
        "MODELS\\CART.PSI",    //995
        "MODELS\\CART.SPT",    //996
        "MODELS\\CHOWQUIN.PSI",//997
        "MODELS\\CHOWQUIN.SPT",//998
        "MODELS\\CLAWARM.PSI", //1001
        "MODELS\\CLAWARM.SPT", //1002
        "MODELS\\CONDUIT.PSI", //1003
        "MODELS\\CONDUIT.SPT", //1004
        "MODELS\\COOLANT.PSI", //1007
        "MODELS\\COOLANT.SPT", //1008
        "MODELS\\COOLBOX.PSI", //1009
        "MODELS\\COOLBOX.SPT", //1010
        "MODELS\\CSWITCH.PSI", //1017
        "MODELS\\CSWITCH.SPT", //1018
        "MODELS\\DCONTROL.PSI",//1019
        "MODELS\\DCONTROL.SPT",//1020
        "MODELS\\DCRATE1.PSI", //1022
        "MODELS\\DCRATE1.SPT", //1023
        "MODELS\\DCRATE1X.PSI",//1024
        "MODELS\\DCRATE1X.SPT",//1025
        "MODELS\\DINEDOOR.PSI",//1030
        "MODELS\\DINEDOOR.SPT",//1031
        "MODELS\\DONG.PSI",    //1032
        "MODELS\\DONG.SPT",    //1033
        "MODELS\\DOOR.PSI",    //1034
        "MODELS\\DOOR.SPT",    //1035
        "MODELS\\DREJ.PSI",    //1036
        "MODELS\\DREJ.SPT",    //1037
        "MODELS\\DREJ_ARM.PSI",//1038
        "MODELS\\DREJ_ARM.SPT",//1039
        "MODELS\\DRJSTGN1.PSI",//1040
        "MODELS\\DS_SHAFT.PSI",//1042
        "MODELS\\DS_SHAFT.SPT",//1043
        "MODELS\\DSDOOR.PSI",  //1046
        "MODELS\\DSDOOR.SPT",  //1047
        "MODELS\\DSDOOR2.PSI", //1048
        "MODELS\\DSDOOR2.SPT", //1049
        "MODELS\\DSLOCK.PSI",  //1050
        "MODELS\\DSLOCK.SPT",  //1051
        "MODELS\\FIRRIKSH.PSI",//1052
        "MODELS\\FIRRIKSH.SPT",//1053
        "MODELS\\FUELRIG.PSI", //1054
        "MODELS\\FUELRIG.SPT", //1055
        "MODELS\\GCRYSTAL.PSI",//1058
        "MODELS\\GCRYSTAL.SPT",//1059
        "MODELS\\GOVCHAIR.PSI",//1060
        "MODELS\\GOVCHAIR.SPT",//1061
        "MODELS\\GOVFAN.PSI",  //1062
        "MODELS\\GOVFAN.SPT",  //1063
        "MODELS\\GOVTABLE.PSI",//1064
        "MODELS\\GOVTABLE.SPT",//1065
        "MODELS\\GRAVGEN.PSI", //1066
        "MODELS\\GUVNA.PSI",   //1068
        "MODELS\\GUVNA.SPT",   //1069
        "MODELS\\HBIKEBOB.PSI",//1070
        "MODELS\\HBIKEBOB.SPT",//1071
        "MODELS\\HOVRBIKE.PSI",//1072
        "MODELS\\IRIS.PSI",    //1078
        "MODELS\\IRIS.SPT",    //1079
        "MODELS\\JUKEBOX.PSI", //1080
        "MODELS\\JUKEBOX.SPT", //1081
        "MODELS\\KCSWITCH.PSI",//1082
        "MODELS\\KCSWITCH.SPT",//1083
        "MODELS\\KORSO.PSI",   //1084
        "MODELS\\KORSO.SPT",   //1085
        "MODELS\\KSWITCH.PSI", //1086
        "MODELS\\KSWITCH.SPT", //1087
        "MODELS\\LASER.PSI",   //1088
        "MODELS\\LASER.SPT",   //1089
        "MODELS\\LIFT.PSI",    //1090
        "MODELS\\LIFT.SPT",    //1091
        "MODELS\\LIFTD.PSI",   //1092
        "MODELS\\LIFTD.SPT",   //1093
        "MODELS\\LIFTU.PSI",   //1094
        "MODELS\\LIFTU.SPT",   //1095
        "MODELS\\LONGBOW.PSI", //1096
        "MODELS\\LONGBOW.SPT", //1097
        "MODELS\\LSHIELD.PSI", //1098
        "MODELS\\LSHIELD.SPT", //1099
        "MODELS\\PHOENIX.PSI", //1100
        "MODELS\\PHOENIX.SPT", //1101
        "MODELS\\PROBE1.PSI",  //1102
        "MODELS\\PROBE1.SPT",  //1103

        "MODELS\\RMRDUMP.PSI",//1112
        "MODELS\\RMRDUMP.SPT",//1113
        "MODELS\\RMRPAD.PSI", //1114
        "MODELS\\RMRPAD.SPT", //1115
        "MODELS\\RUBBLE1.PSI",//1118
        "MODELS\\RUBBLE1.SPT",//1119

        "MODELS\\SHUTTLE.PSI",//1136

        "MODELS\\SLAVEGRD.PSI",//1141
        "MODELS\\SLAVEGRD.SPT",//1142
        "MODELS\\STEAMBOX.PSI",//1145
        "MODELS\\STEAMBOX.SPT",//1146
        "MODELS\\STITH.PSI",   //1147
        "MODELS\\STITH.SPT",   //1148

        "MODELS\\SWITCH.PSI", //1153
        "MODELS\\SWITCH.SPT", //1154
        "MODELS\\T14DOOR.PSI",//1155
        "MODELS\\T14DOOR.SPT",//1156

        "MODELS\\T14LOCK.PSI",//1159
        "MODELS\\T14LOCK.SPT",//1160
        "MODELS\\TARGET.PSI", //1165
        "MODELS\\TEK.PSI",    //1169
        "MODELS\\TEK.SPT",    //1170

        "MODELS\\VALKYRIE.PSI",//1180
        "MODELS\\VALKYRIE.SPT",//1181

        "MODELS\\VLONGBOW.PSI",//1190
        "MODELS\\VLONGBOW.SPT",//1191
        "MODELS\\VMACHINE.PSI",//1192
        "MODELS\\VMACHINE.SPT",//1193

        "MODELS\\VP_VENT.PSI",//1198
        "MODELS\\VP_VENT.SPT",//1199
        "MODELS\\WALLFAN.PSI",//1202
        "MODELS\\WALLFAN.SPT",//1203
        "MODELS\\WALLPST.PSI",//1204
        "MODELS\\WALLPST.SPT",//1205

        "MODELS\\GAUOLFLY.PSI",//1224
        "MODELS\\GAUOLFLY.SPT",//1225

        "MODELS\\SESHCLAW.PSI",  //1232
        "MODELS\\SESHCLAW.SPT",  //1233
        "MODELS\\SESHTRAP.PSI",  //1238
        "MODELS\\SESHTRAP.SPT",  //1239
        "MODELS\\DMFBEAM.PSI",   //1240
        "MODELS\\DMFBEAM.SPT",   //1241
        "MODELS\\HOVERGUN.PSI",  //1242
        "MODELS\\HOVERGUN.SPT",  //1243
        "STRTMENU\\COMING1.RAW", //1244
        "STRTMENU\\COMING2.RAW", //1245
        "STRTMENU\\COMING3.RAW", //1246
        "STRTMENU\\COMING4.RAW", //1247
        "STRTMENU\\CSELECT.RAW", //1248
        "STRTMENU\\ESETUP.RAW",  //1249
        "STRTMENU\\FSETUP.RAW",  //1250
        "STRTMENU\\GAMEOVER.RAW",//1251
        "STRTMENU\\LAYER1.PSI",  //1252
        "STRTMENU\\STARGRID.PSI",//1257
        "STRTMENU\\STARMAP.PSI", //1258
        "STRTMENU\\STARMAP.SPT", //1259
        "STRTMENU\\STRTMENU.RAW",//1261
        "BIN\\RADDRAW5.BIN",     //1263
        "BIN\\RADDRAW3.BIN",     //1264
        "BIN\\RADDRAW4.BIN",     //1265
        "BIN\\RADDRAW2.BIN",     //1266

        "BIN\\EXPLORE.BIN",  //1268
        "BIN\\FLYING.BIN",   //1269
        "BIN\\EXAITAU1.BIN", //1270
        "BIN\\EXAIVIGO.BIN", //1271
        "BIN\\EXAITRAD.BIN", //1272
        "BIN\\EXAIDERE.BIN", //1273
        "BIN\\MENU.BIN",     //1274
        "BIN\\FLYBOSS.BIN",  //1275
        "BIN\\FLYBOSS2.BIN", //1276
        "BIN\\EXAISESH.BIN", //1277
        "BIN\\FLYSHUTL.BIN", //1278
        "BIN\\FLYGAOUL.BIN", //1279
        "BIN\\RADRACE.BIN",  //1280
        "SOUND\\BANGKOK.SBH",//1281

        "SOUND\\CRASH.SBB",  //1283
        "SOUND\\BANGKOK.SBB",//1284
        "SOUND\\CRASH.SBH",  //1285

        "SOUND\\EXPLORE.SBB",//1290
        "SOUND\\EXPLORE.SBH",//1291

        "SOUND\\SPACE1.SBB",//1293

        "SOUND\\FRONTEND.SBB",//1295
        "SOUND\\FRONTEND.SBH",//1296

        "SOUND\\SPACE1.SBH",//1298
        "SOUND\\BOSS1.SBB", //1299

        "SOUND\\BOSS1.SBH",//1301

        "SOUND\\VOLCANO.SBB",//1305
        "SOUND\\VOLCANO.SBH",//1306

        "SOUND\\SESHARIM.SBH",//1308
        "SOUND\\SESHARIM.SBB",//1309
