/* SPDX-License-Identifier: MIT */
/* Copyright © 2017-2022 Mark E Sowden <hogsy@oldtimes-software.com> */

/* Titan A.E. */
"GAMETEXT.TXT",                                  //0
        "EXPLORE\\PICKUPS\\AMMO1.PSI",           //306
        "EXPLORE\\PICKUPS\\AMMO1.SPT",           //307
        "EXPLORE\\PICKUPS\\CAN.PSI",             //308
        "EXPLORE\\PICKUPS\\CAN.SPT",             //309
        "EXPLORE\\PICKUPS\\COOLANT.PSI",         //310
        "EXPLORE\\PICKUPS\\COOLANT.SPT",         //311
        "EXPLORE\\PICKUPS\\COOLBOX.PSI",         //312
        "EXPLORE\\PICKUPS\\COOLBOX.SPT",         //313
        "EXPLORE\\PICKUPS\\CRYSTBIT.PSI",        //314
        "EXPLORE\\PICKUPS\\CRYSTBIT.SPT",        //315
        "EXPLORE\\PICKUPS\\DONG.PSI",            //316
        "EXPLORE\\PICKUPS\\DONG.SPT",            //317
        "EXPLORE\\PICKUPS\\GUN1.PSI",            //318
        "EXPLORE\\PICKUPS\\GUN1.SPT",            //319
        "EXPLORE\\PICKUPS\\HEALTH1.PSI",         //320
        "EXPLORE\\PICKUPS\\HEALTH1.SPT",         //321
        "EXPLORE\\PICKUPS\\MEDPACK.PSI",         //322
        "EXPLORE\\PICKUPS\\MEDPACK.SPT",         //323
        "EXPLORE\\PICKUPS\\MEDPROBE.PSI",        //324
        "EXPLORE\\PICKUPS\\MEDPROBE.SPT",        //325
        "EXPLORE\\PICKUPS\\RD_KEY.PSI",          //326
        "EXPLORE\\PICKUPS\\RD_KEY.SPT",          //327
        "EXPLORE\\PICKUPS\\RD_KEY2.PSI",         //328
        "EXPLORE\\PICKUPS\\RD_KEY2.SPT",         //329
        "EXPLORE\\PICKUPS\\TRANSL8R.PSI",        //332
        "EXPLORE\\PICKUPS\\TRANSL8R.SPT",        //333
        "EXPLORE\\PICKUPS\\VP_CHIP.PSI",         //334
        "EXPLORE\\PICKUPS\\VP_CHIP.SPT",         //335
        "EXPLORE\\PICKUPS\\VP_KEY.PSI",          //336
        "EXPLORE\\PICKUPS\\VP_KEY.SPT",          //337
        "EXPLORE\\PICKUPS\\WRENCH.PSI",          //338
        "EXPLORE\\PICKUPS\\WRENCH.SPT",          //339
        "EXPLORE\\PICKUPS\\JAWBONE.PSI",         //351
        "EXPLORE\\PICKUPS\\JAWBONE.SPT",         //352
        "EXPLORE\\PICKUPS\\CLAWBONE.PSI",        //353
        "EXPLORE\\PICKUPS\\CLAWBONE.SPT",        //354
        "EXPLORE\\WEAPONS\\CALEGUN1.PSI",        //398
        "EXPLORE\\WEAPONS\\CALEGUN1.SPT",        //399
        "EXPLORE\\WEAPONS\\WEAP.SPT",            //401
        "EXPLORE\\WEAPONS\\WRENCH.PSI",          //402
        "EXPLORE\\WEAPONS\\WRENCH.SPT",          //403
        "EXPLORE\\WEAPONS\\PROJECT\\MISSILE.PSI",//404
        "EXPLORE\\WEAPONS\\PROJECT\\MISSILE.SPT",//405
        "EXPLORE\\WEAPONS\\PROJECT\\SPIT.PSI",   //406
        "EXPLORE\\WEAPONS\\PROJECT\\SPIT.SPT",   //407
        "EXPLORE\\WEAPONS\\JAWBONE.PSI",         //410
        "EXPLORE\\WEAPONS\\JAWBONE.SPT",         //411
        "EXPLORE\\WEAPONS\\CLAWBONE.PSI",        //412
        "EXPLORE\\WEAPONS\\CLAWBONE.SPT",        //413
        "EXPLORE\\WRISTCOM\\IMAGES.SPT",         //414
        "EXPLORE\\WRISTCOM\\WRISTCOM.PSI",       //415
        "EXPLORE\\WRISTCOM\\WRISTCOM.SPT",       //416
        "FLYING\\BACKDRPS\\ENDSCN1.RAW",         //428
        "FLYING\\BACKDRPS\\ENDSCN2.RAW",         //429
        "FLYING\\BACKDRPS\\ENDSCN3.RAW",         //430
        "EXPLORE\\ALIENFNT\\ALIEN1.SPT",         //422
        "EXPLORE\\OSD\\CODEFRAG.SPT",            //424
        "FLYING\\GLOBAL.SPT",                    //426
        "FLYING\\OBJECTS\\PICKUP_B.PSI",         //553
        "FLYING\\OBJECTS\\MISSILE.PSI",          //661
        "FLYING\\OBJECTS\\MISSILE.SPT",          //662
        "FLYING\\OBJECTS\\NME_SHOT.PSI",         //663
        "FLYING\\OBJECTS\\HOVRBAR.PSI",          //770
        "FLYING\\OBJECTS\\HOVRBAR.SPT",          //771
        "FLYING\\OBJECTS\\SHKWAVE.PSI",          //762
        "FLYING\\OBJECTS\\SHKWAVE.SPT",          //763
        "FLYING\\SPRITES\\BOBSRING.SPR",         //793
        "FLYING\\SPRITES\\FRNKBALL.SPR",         //857
        "FLYING\\SPRITES\\KEYSPR.SPR",           //878
        "GRAPHICS\\ENVRO.SPT",                   //921
        "GRAPHICS\\EXP_BLUE.PAL",                //922
        "GRAPHICS\\EXP_DREJ.PAL",                //923
        "GRAPHICS\\EXP_GREN.PAL",                //925
        "GRAPHICS\\EXP_NEG.PAL",                 //926
        "GRAPHICS\\EXP_RED.PAL",                 //928
        "GRAPHICS\\EXP_WOOD.PAL",                //929
        "GRAPHICS\\EXPLODE1.SPT",                //930
        "GRAPHICS\\FONT12A.FON",                 //934
        "GRAPHICS\\FONT18.FON",                  //935
        "GRAPHICS\\GEN_OVER.SPT",                //936
        "GRAPHICS\\KORSO.SPT",                   //937
        "GRAPHICS\\LENSFLAR.SPT",                //938
        "GRAPHICS\\PARTICLES.SPT",               //940
        "GRAPHICS\\TITANGEN.SPT",                //944
        "GRAPHICS\\TRAILS.SPT",                  //945
        "GRAPHICS\\FRONTEND\\MENU.RAW",          //951
        "GRAPHICS\\LONGBOW.SPT",                 //965
        "GRAPHICS\\PHOENIX.SPT",                 //966
        "GRAPHICS\\SHUTTLE.SPT",                 //967
        "GRAPHICS\\VALKYRIE.SPT",                //968
        "MODELS\\AKIMA.PSI",                     //969
        "MODELS\\AKIMA.SPT",                     //970
        "MODELS\\BADBIKE.PSI",                   //971
        "MODELS\\BARMAN.PSI",                    //973
        "MODELS\\BARMAN.SPT",                    //974
        "MODELS\\BARREL.PSI",                    //979
        "MODELS\\BARREL.SPT",                    //980
        "MODELS\\BARREL1.PSI",                   //981
        "MODELS\\BIGFAN.PSI",                    //989
        "MODELS\\BIGFAN.SPT",                    //990
        "MODELS\\BIGHEAD.PSI",                   //991
        "MODELS\\BIGHEAD.SPT",                   //992
        "MODELS\\CALE.PSI",                      //993
        "MODELS\\CALE.SPT",                      //994
        "MODELS\\CART.PSI",                      //995
        "MODELS\\CART.SPT",                      //996
        "MODELS\\CLAWARM.PSI",                   //1001
        "MODELS\\CLAWARM.SPT",                   //1002
        "MODELS\\CONDUIT.PSI",                   //1003
        "MODELS\\CONDUIT.SPT",                   //1004
        "MODELS\\COOLANT.PSI",                   //1007
        "MODELS\\COOLANT.SPT",                   //1008
        "MODELS\\COOLBOX.PSI",                   //1009
        "MODELS\\COOLBOX.SPT",                   //1010
        "MODELS\\DCONTROL.PSI",                  //1019
        "MODELS\\DCONTROL.SPT",                  //1020
        "MODELS\\DCRATE1.PSI",                   //1022
        "MODELS\\DINEDOOR.PSI",                  //1030
        "MODELS\\DINEDOOR.SPT",                  //1031
        "MODELS\\DONG.PSI",                      //1032
        "MODELS\\DONG.SPT",                      //1033
        "MODELS\\DOOR.PSI",                      //1034
        "MODELS\\DOOR.SPT",                      //1035
        "MODELS\\DREJ.PSI",                      //1036
        "MODELS\\DREJ.SPT",                      //1037
        "MODELS\\DREJ_ARM.PSI",                  //1038
        "MODELS\\DREJ_ARM.SPT",                  //1039
        "MODELS\\DRJSTGN1.PSI",                  //1040
        "MODELS\\DS_SHAFT.PSI",                  //1042
        "MODELS\\DS_SHAFT.SPT",                  //1043
        "MODELS\\DSDOOR.PSI",                    //1046
        "MODELS\\DSDOOR.SPT",                    //1047
        "MODELS\\DSDOOR2.PSI",                   //1048
        "MODELS\\DSDOOR2.SPT",                   //1049
        "MODELS\\DSLOCK.PSI",                    //1050
        "MODELS\\DSLOCK.SPT",                    //1051
        "MODELS\\FUELRIG.PSI",                   //1054
        "MODELS\\FUELRIG.SPT",                   //1055
        "MODELS\\GCRYSTAL.PSI",                  //1058
        "MODELS\\GCRYSTAL.SPT",                  //1059
        "MODELS\\GOVCHAIR.PSI",                  //1060
        "MODELS\\GOVCHAIR.SPT",                  //1061
        "MODELS\\GOVFAN.PSI",                    //1062
        "MODELS\\GOVFAN.SPT",                    //1063
        "MODELS\\GOVTABLE.PSI",                  //1064
        "MODELS\\GOVTABLE.SPT",                  //1065
        "MODELS\\GRAVGEN.PSI",                   //1066
        "MODELS\\GUVNA.PSI",                     //1068
        "MODELS\\GUVNA.SPT",                     //1069
        "MODELS\\HBIKEBOB.PSI",                  //1070
        "MODELS\\HOVRBIKE.PSI",                  //1072
        "MODELS\\IRIS.PSI",                      //1078
        "MODELS\\IRIS.SPT",                      //1079
        "MODELS\\JUKEBOX.PSI",                   //1080
        "MODELS\\JUKEBOX.SPT",                   //1081
        "MODELS\\KCSWITCH.PSI",                  //1082
        "MODELS\\KCSWITCH.SPT",                  //1083
        "MODELS\\KORSO.PSI",                     //1084
        "MODELS\\KORSO.SPT",                     //1085
        "MODELS\\KSWITCH.PSI",                   //1086
        "MODELS\\KSWITCH.SPT",                   //1087
        "MODELS\\LASER.PSI",                     //1088
        "MODELS\\LASER.SPT",                     //1089
        "MODELS\\LIFT.PSI",                      //1090
        "MODELS\\LIFT.SPT",                      //1091
        "MODELS\\LIFTD.PSI",                     //1092
        "MODELS\\LIFTD.SPT",                     //1093
        "MODELS\\LIFTU.PSI",                     //1094
        "MODELS\\LIFTU.SPT",                     //1095
        "MODELS\\LONGBOW.PSI",                   //1096
        "MODELS\\LONGBOW.SPT",                   //1097
        "MODELS\\LSHIELD.PSI",                   //1098
        "MODELS\\LSHIELD.SPT",                   //1099
        "MODELS\\PHOENIX.PSI",                   //1100
        "MODELS\\PHOENIX.SPT",                   //1101
        "MODELS\\PROBE1.PSI",                    //1102
        "MODELS\\PROBE1.SPT",                    //1103
        "MODELS\\RMRDUMP.PSI",                   //1112
        "MODELS\\RMRDUMP.SPT",                   //1113
        "MODELS\\RMRPAD.PSI",                    //1114
        "MODELS\\RMRPAD.SPT",                    //1115
        "MODELS\\RUBBLE1.PSI",                   //1118
        "MODELS\\RUBBLE1.SPT",                   //1119
        "MODELS\\SHUTTLE.PSI",                   //1136
        "MODELS\\SLAVEGRD.PSI",                  //1141
        "MODELS\\SLAVEGRD.SPT",                  //1142
        "MODELS\\STEAMBOX.PSI",                  //1145
        "MODELS\\STITH.PSI",                     //1147
        "MODELS\\STITH.SPT",                     //1148
        "MODELS\\SWITCH.PSI",                    //1153
        "MODELS\\SWITCH.SPT",                    //1154
        "MODELS\\TARGET.PSI",                    //1165
        "MODELS\\TEK.PSI",                       //1169
        "MODELS\\TEK.SPT",                       //1170
        "MODELS\\VALKYRIE.PSI",                  //1180
        "MODELS\\VALKYRIE.SPT",                  //1181
        "MODELS\\VLONGBOW.PSI",                  //1190
        "MODELS\\VLONGBOW.SPT",                  //1191
        "MODELS\\VMACHINE.PSI",                  //1192
        "MODELS\\VMACHINE.SPT",                  //1193
        "MODELS\\VP_VENT.PSI",                   //1198
        "MODELS\\VP_VENT.SPT",                   //1199
        "MODELS\\GAUOLFLY.PSI",                  //1224
        "MODELS\\GAUOLFLY.SPT",                  //1225
        "MODELS\\SESHCLAW.PSI",                  //1232
        "MODELS\\SESHCLAW.SPT",                  //1233
        "MODELS\\SESHTRAP.PSI",                  //1238
        "MODELS\\SESHTRAP.SPT",                  //1239
        "MODELS\\DMFBEAM.PSI",                   //1240
        "MODELS\\DMFBEAM.SPT",                   //1241
        "MODELS\\HOVERGUN.PSI",                  //1242
        "MODELS\\HOVERGUN.SPT",                  //1243
        "STRTMENU\\COMING1.RAW",                 //1244
        "STRTMENU\\COMING2.RAW",                 //1245
        "STRTMENU\\COMING3.RAW",                 //1246
        "STRTMENU\\COMING4.RAW",                 //1247
        "STRTMENU\\CSELECT.RAW",                 //1248
        "STRTMENU\\ESETUP.RAW",                  //1249
        "STRTMENU\\FSETUP.RAW",                  //1250
        "STRTMENU\\GAMEOVER.RAW",                //1251
        "STRTMENU\\STARGRID.PSI",                //1257
        "STRTMENU\\STARMAP.PSI",                 //1258
        "STRTMENU\\STARMAP.SPT",                 //1259
        "STRTMENU\\STRTMENU.RAW",                //1261
        "BIN\\RADDRAW5.BIN",                     //1263
        "BIN\\RADDRAW3.BIN",                     //1264
        "BIN\\RADDRAW4.BIN",                     //1265
        "BIN\\RADDRAW2.BIN",                     //1266
        "BIN\\EXPLORE.BIN",                      //1268
        "BIN\\FLYING.BIN",                       //1269
        "BIN\\EXAITAU1.BIN",                     //1270
        "BIN\\EXAIVIGO.BIN",                     //1271
        "BIN\\EXAITRAD.BIN",                     //1272
        "BIN\\EXAIDERE.BIN",                     //1273
        "BIN\\MENU.BIN",                         //1274
        "BIN\\FLYBOSS.BIN",                      //1275
        "BIN\\FLYBOSS2.BIN",                     //1276
        "BIN\\EXAISESH.BIN",                     //1277
        "BIN\\FLYSHUTL.BIN",                     //1278
        "BIN\\FLYGAOUL.BIN",                     //1279
        "BIN\\RADRACE.BIN",                      //1280

        "EXPLORE\\REPLAYS\\VOLCDEMO.RPL",
        "EXPLORE\\LEVELS\\FLATMAP.RAD",
